### ISSUE TITLE
能否给出运行改代码的环境依赖

### ISSUE THREAD

**Issue by lemuria-wchen** [THUIR/T2Ranking#5]
运行报错，pandas 版本会有影响。

**Comment by lemuria-wchen** [comment]
在读取csv文件的时候，都会用到 header=None，但实际上，给出的所有文件，都是有行名的

pd.read_csv(args.collection,sep="\t",header=None, quoting=3)

**Comment by CSQianDong** [comment]
你好，这个bug已经修复，请重新pull一下最新代码。不是pandas版本导致的，huggingface上的数据因为要展示做Preview，header是后加的。感谢汇报。

**Comment by CSQianDong** [comment]
已更新requirements.txt @lemuria-wchen
