### ISSUE TITLE
关于 cross encoder 源码的疑问

### ISSUE THREAD

**Issue by habaneraa** [THUIR/T2Ranking#9]
您好，我想请教一点问题。关于 cross encoder baseline 的源码：

https://github.com/THUIR/T2Ranking/blob/d28af5182c6d767306c2839fa27ce6cd360feb03/src/modeling.py#L37-L41

这里的目标 label 为何是全 0 值而非 `qrels.train` 中的 `rel` 相关度分数呢？

**Comment by CSQianDong** [comment]
位置0放的都是positive
